image: debian/stable
sources:
  - https://git.sr.ht/~swisschili/bluejay
packages:
  - build-essential
  - gcc-multilib
  - m4
  - python3
  - gawk
  - nasm
  - texlive
  - texlive-latex-extra
  - texlive-xetex
  - global
tasks:
  - build-kernel: |
      cd bluejay
      ./bin/jmk
      cd src/kernel
      make
  - build-lisp: |
      cd bluejay
      ./bin/jmk
      cd src/lisp
      make
  - build-latex: |
      cd bluejay
      ./bin/jmk
      cd doc/lisp_reference
      make
artifacts:
  - bluejay/src/lisp/lisp
  - bluejay/src/kernel/kernel.elf
  - bluejay/doc/lisp_reference/lisp_reference.pdf
