.TH building 9 "13 March 2021" "1" "Building the kernel"
.SH SYNOPSIS
Bluejay uses the JMK build system, a simple M4 script that generates Makefiles.
Use the jmk binary in bin/ to generate Makefiles, then build the kernel with the
Makefile in src/kernel/.
.SH DESCRIPTION
The included Makefile provides several targets useful for building and
debugging the kernel.  Here are the useful targets:

kernel.elf:  compile multiboot kernel

qemu:        run multiboot kernel in qemu

debug:       run qemu with debug server and attach gdb

install:     build bootable grub image in /bin/bluejay.iso

qemu-iso:    boot the iso file

clean:       delete build artifacts
.SH SEE ALSO
jmk(1)
